name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.0, 20.18.0, latest]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Install dependencies
        run: npm ci
      -
        name: Run tests
        run: npm test
