name: Build image and publish to Docker Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: 343dev/optimizt
  IMAGE_PLATFORMS: linux/amd64,linux/arm64

permissions:
  contents: read

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Define variables
        id: package
        run: |
          version=$(node -p "require('./package.json').version")
          echo "pkg_version=${version}" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          push: true
          platforms: ${{ env.IMAGE_PLATFORMS }}
          tags: ${{ env.IMAGE_NAME }}:${{ steps.package.outputs.pkg_version }},${{ env.IMAGE_NAME }}:latest
